csgo:
  ak-47:
    horizontal_range: 0
    min_vertical: 1
    max_vertical: 2
    min_firerate: 0.03
    max_firerate: 0.04
    bonus_offset: 'max(0.25, (max(0.25,3.5 + (-0.20 + start - time.time()))))'
    horizontal_offset: '(-horizontal_range * offset_const) / offset_const'
    vertical_offset: '(random.randrange(min_vertical * offset_const, max_vertical * offset_const, 1) * bonus_offset) / offset_const'
    time_offset: '(random.randrange(min_firerate * offset_const, max_firerate * offset_const, 1) / bonus_offset) / offset_const'
  m4a1-s:
    horizontal_range: 0
    min_vertical: 2
    max_vertical: 3
    min_firerate: 0.02
    max_firerate: 0.03
    bonus_offset: 'max(0.25, (max(0.25,3.5 + (-0.30 + start - time.time()))))'
    horizontal_offset: '(-horizontal_range * offset_const) / offset_const'
    vertical_offset: '(random.randrange(min_vertical * offset_const, max_vertical * offset_const, 1)  * bonus_offset) / offset_const'
    time_offset: '(random.randrange(min_firerate * offset_const, max_firerate * offset_const, 1) / bonus_offset) / offset_const'
  m4a4:
    horizontal_range: 0
    min_vertical: 2
    max_vertical: 3
    min_firerate: 0.02
    max_firerate: 0.03
    bonus_offset: 'max(0.25, (max(0.25,4 + (-0.5 + start - time.time()))))'
    horizontal_offset: '(-horizontal_range * offset_const) / offset_const'
    vertical_offset: '(random.randrange(min_vertical * offset_const, max_vertical * offset_const, 1) * bonus_offset) / offset_const'
    time_offset: '(random.randrange(min_firerate * offset_const, max_firerate * offset_const, 1) / bonus_offset) / offset_const'
  galil ar:
    horizontal_range: 1
    min_vertical: 1
    max_vertical: 2
    min_firerate: 0.02
    max_firerate: 0.03
    bonus_offset: 'max(0.25, (max(0.25,4 + (-0.5 + start - time.time()))))'
    horizontal_offset: '(horizontal_range * offset_const) / offset_const'
    vertical_offset: '(random.randrange(min_vertical * offset_const, max_vertical * offset_const, 1)  * bonus_offset) / offset_const'
    time_offset: '(random.randrange(min_firerate * offset_const, max_firerate * offset_const, 1) / bonus_offset) / offset_const'
