warzone-modern warfare:
  m13:
    horizontal_range: 0
    min_vertical: 1
    max_vertical: 2
    min_firerate: 0.03
    max_firerate: 0.04
    bonus_offset: 'max(0.25, (max(0.25,2 + (start - time.time()))))'
    horizontal_offset: '(-horizontal_range * offset_const) / offset_const'
    vertical_offset: '(random.randrange(min_vertical * offset_const, max_vertical * offset_const, 1) / bonus_offset) / offset_const'
    time_offset: '(random.randrange(min_firerate * offset_const, max_firerate * offset_const, 1) * bonus_offset) / offset_const'
  m4a1:
    horizontal_range: 0
    min_vertical: 1
    max_vertical: 2
    min_firerate: 0.05
    max_firerate: 0.06
    bonus_offset: 'max(0.25, (max(0.25,3 + (-0.20 + start - time.time()))))'
    horizontal_offset: '(-horizontal_range * offset_const) / offset_const'
    vertical_offset: '(random.randrange(min_vertical * offset_const, max_vertical * offset_const, 1) * bonus_offset) / offset_const'
    time_offset: '(random.randrange(min_firerate * offset_const, max_firerate * offset_const, 1) / bonus_offset) / offset_const'
  fr 5.56:
  ak-47:
  fal:
  fn scar 17:
  oden:
  kilo 141:
  ram-7:
  grau 5.56:
  cr-56 amax (galil):
  an-94:
  as val:
  fara 83:
