## Configuration
untitled zombie game:
  glock:
  acc_honey_badger:
  p90:
apex:
  alternator:
  spitfire:
  rampage:
  havoc:
  volt:
  flatline:
  r-301:
  tester:
  car:
  r99:
  re-45:
fortnite:
  assualt rifle:
  smg:
csgo:
  ak-47:
  m4a1-s:
  m4a4:
  galil ar:
warzone-vanguard:
  stg44:
  automaton:
  itra burst:
  bar:
  as44:
  nz-41:
  volk:
  cooper carbine:
  mp-40:
  sten:
  m1928:
  owen gun:
  type 100:
  ppsh-41:
  welgun:
  mg42:
  dp27:
  type 11:
  bren:
warzone-modern warfare:
  m13:
  m4a1:
  fr 5.56:
  ak-47:
  fal:
  fn scar 17:
  oden:
  kilo 141:
  ram-7:
  grau 5.56:
  cr-56 amax (galil):
  an-94:
  as val:
  fara 83:






